name: Build résumé

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile résumé
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: current
          root_file: EleanorNicolsonResume.tex

      - name: Upload built PDF
        uses: actions/upload-artifact@v4
        with:
          name: EleanorNicolsonResume
          path: current/EleanorNicolsonResume.pdf
